/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module button_regulator_10 (
    input clk,
    input in,
    input [15:0] input_read,
    output reg write_en,
    output reg [15:0] out
  );
  
  
  
  wire [1-1:0] M_regulator_map_inp;
  wire [1-1:0] M_regulator_input_write_enable;
  wire [16-1:0] M_regulator_input_write_data;
  reg [1-1:0] M_regulator_inp;
  reg [16-1:0] M_regulator_map_out;
  reg [16-1:0] M_regulator_input_read;
  input_regulator_21 regulator (
    .clk(clk),
    .inp(M_regulator_inp),
    .map_out(M_regulator_map_out),
    .input_read(M_regulator_input_read),
    .map_inp(M_regulator_map_inp),
    .input_write_enable(M_regulator_input_write_enable),
    .input_write_data(M_regulator_input_write_data)
  );
  
  wire [1-1:0] M_map_out;
  reg [1-1:0] M_map_in;
  buffer_22 map (
    .in(M_map_in),
    .out(M_map_out)
  );
  
  always @* begin
    M_regulator_inp = in;
    M_map_in = M_regulator_map_inp;
    M_regulator_map_out[0+0-:1] = M_map_out;
    M_regulator_map_out[1+14-:15] = 15'h0000;
    M_regulator_input_read = input_read;
    write_en = M_regulator_input_write_enable;
    out = M_regulator_input_write_data;
  end
endmodule
