/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     DELAY_CYCLE_COUNT = PIPELINE_CYCLE_COUNT
*/
module input_pipeline_30 (
    input clk,
    input in,
    output reg out
  );
  
  localparam DELAY_CYCLE_COUNT = 3'h5;
  
  
  reg [4:0] M_pipe_d, M_pipe_q = 1'h0;
  
  integer i;
  
  always @* begin
    M_pipe_d = M_pipe_q;
    
    M_pipe_d[0+0-:1] = in;
    for (i = 1'h1; i < 3'h5; i = i + 1) begin
      M_pipe_d[(i)*1+0-:1] = M_pipe_q[(i - 1'h1)*1+0-:1];
    end
    out = M_pipe_q[4+0-:1];
  end
  
  always @(posedge clk) begin
    M_pipe_q <= M_pipe_d;
  end
  
endmodule
