/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module pc_incrementer_16_13 (
    input [15:0] in,
    output reg [15:0] out
  );
  
  
  
  reg [14:0] cout;
  
  always @* begin
    out[0+0-:1] = in[0+0-:1] ^ 1'h1;
    cout[0+0-:1] = in[0+0-:1] & 1'h1;
    out[1+14-:15] = in[1+14-:15] ^ cout[0+14-:15];
    cout[1+13-:14] = in[1+13-:14] & cout[0+13-:14];
  end
endmodule
