/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module buffer_22 (
    input in,
    output reg out
  );
  
  
  
  always @* begin
    out = in;
  end
endmodule
