/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     ALUFN_NOOP = 6b000011
     ALUFN_AND = 6b000010
     ALUFN_SHL = 6b000001
     ALUFN_ADD = 6b000000
     ALUFN_SHRC = 6b100001
     CONTROL_SIG = {c{1b0,1b0,1b0,1b0,ALUFN_NOOP,1b0,1b0},c{1b0,1b0,1b0,1b0,ALUFN_NOOP,1b0,1b0},c{1b0,1b0,1b0,1b0,ALUFN_NOOP,1b0,1b0},c{1b0,1b0,1b0,1b0,ALUFN_NOOP,1b0,1b0},c{1b0,1b0,1b0,1b0,ALUFN_NOOP,1b0,1b0},c{1b0,1b0,1b0,1b0,ALUFN_NOOP,1b0,1b0},c{1b0,1b0,1b0,1b0,ALUFN_NOOP,1b0,1b0},c{1b0,1b0,1b1,1b0,ALUFN_SHRC,1b0,1b1},c{1b1,1b1,1b0,1b0,ALUFN_NOOP,1b0,1b0},c{1b0,1b1,1b1,1b0,ALUFN_ADD,1b1,1b0},c{1b0,1b0,1b1,1b1,ALUFN_ADD,1b0,1b1},c{1b0,1b0,1b1,1b0,ALUFN_ADD,1b0,1b1},c{1b0,1b0,1b0,1b0,ALUFN_AND,1b0,1b1},c{1b0,1b0,1b0,1b0,ALUFN_SHL,1b0,1b1},c{1b0,1b0,1b0,1b0,ALUFN_ADD,1b0,1b1},c{1b0,1b0,1b0,1b0,ALUFN_NOOP,1b0,1b0}}
*/
module control_unit_4 (
    input rst,
    input z,
    input [3:0] opcode,
    output reg pcsel,
    output reg ra2sel,
    output reg bsel,
    output reg wdsel,
    output reg [5:0] alufn,
    output reg wr,
    output reg werf
  );
  
  localparam ALUFN_NOOP = 6'h03;
  localparam ALUFN_AND = 6'h02;
  localparam ALUFN_SHL = 6'h01;
  localparam ALUFN_ADD = 6'h00;
  localparam ALUFN_SHRC = 6'h21;
  localparam CONTROL_SIG = 192'h00c00c00c00c00c00c00c285c0c60230120100900500100c;
  
  
  always @* begin
    pcsel = CONTROL_SIG[(opcode[0+3-:4])*12+11+0-:1] & z;
    ra2sel = CONTROL_SIG[(opcode[0+3-:4])*12+10+0-:1];
    bsel = CONTROL_SIG[(opcode[0+3-:4])*12+9+0-:1];
    wdsel = CONTROL_SIG[(opcode[0+3-:4])*12+8+0-:1];
    alufn = CONTROL_SIG[(opcode[0+3-:4])*12+2+5-:6];
    wr = CONTROL_SIG[(opcode[0+3-:4])*12+1+0-:1] & (~rst);
    werf = CONTROL_SIG[(opcode[0+3-:4])*12+0+0-:1] & (~rst);
  end
endmodule
