/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module grid_selector_25 (
    input [3:0] select,
    input [143:0] grid,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    
    case (select[0+3-:4])
      1'h0: begin
        out = grid[0+15-:16];
      end
      1'h1: begin
        out = grid[16+15-:16];
      end
      2'h2: begin
        out = grid[32+15-:16];
      end
      2'h3: begin
        out = grid[48+15-:16];
      end
      3'h4: begin
        out = grid[64+15-:16];
      end
      3'h5: begin
        out = grid[80+15-:16];
      end
      3'h6: begin
        out = grid[96+15-:16];
      end
      3'h7: begin
        out = grid[112+15-:16];
      end
      4'h8: begin
        out = grid[128+15-:16];
      end
      default: begin
        out = 16'h0000;
      end
    endcase
  end
endmodule
